### ISSUE TITLE
Update Philly Hip Production to 1.20

### ISSUE THREAD

**Issue by ronardcaktus** [caktus/philly-hip#218]
- [x] Coordinate and notify team of the update
- [x] Update Ansible roles
caktus.k8s-web-cluster to v1.1.0
caktus.django-k8s to v1.4.0
caktus.k8s-hosting-services to v0.3.0
- [x] Update to Kubernetes 1.20
- [x] Update [ingress-nginx](https://github.com/kubernetes/ingress-nginx/releases) to helm chart version `3.39.0` (`v0.49.3` ingress-nginx)
- [x] Update [cert-manager](https://github.com/jetstack/cert-manager/releases) to helm chart version `1.6.1`
- [x] Update node groups to 1.20 AMIs [5m downtime]
- [x] Update [aws_fluent_bit](https://artifacthub.io/packages/helm/aws/aws-for-fluent-bit) to `0.1.11`
- [ ] ~Update nri-bundle to 3.2.4~
- [x] Check logs for deprecation and other warnings of breakage
- [x] Create pull request

**Comment by Scottm-Caktus** [comment]
Went Smoothly
